#!/bin/bash

if [ $1 = 'video' ]; 
then
# 	xbacklight -set 100

    # magic bright: Sport
    ddccontrol -r 0xdc -w 4 dev:/dev/i2c-1
    
    # гамма
	xgamma -gamma 1.0
else
    # гамма
    xgamma -gamma 0.65
fi

if [ $1 = 'night' ]; 
then
    # magic bright: Text
    ddccontrol -r 0xdc -w 1 dev:/dev/i2c-1
fi

if [ $1 = 'text' ]; 
then
    # magic bright: Game
    ddccontrol -r 0xdc -w 3 dev:/dev/i2c-1
fi

exit 0
